In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = "Resources/analytic_data2022.csv"
# DataSource 1: https://www.countyhealthrankings.org/sites/default/files/analytic_data2022.csv
# DataSource 2: https://www.countyhealthrankings.org/sites/default/files/DataDictionary_2022.pdf
health_df = pd.read_csv(file_path)
health_df

/var/folders/fx/3xjkq6_j0w52ql5m_lv0vsbr0000gn/T/ipykernel_2354/2863528333.py:4: DtypeWarning: Columns (0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724) have mixed types. Specify dtype option on import or set low_memory=False.
  health_df = pd.read_csv(file_path)

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% female raw value,% female numerator,% female denominator,% female CI low,% female CI high,% rural raw value,% rural numerator,% rural denominator,% rural CI low,% rural CI high
0,statecode,countycode,fipscode,state,county,year,county_ranked,v001_rawvalue,v001_numerator,v001_denominator,...,v057_rawvalue,v057_numerator,v057_denominator,v057_cilow,v057_cihigh,v058_rawvalue,v058_numerator,v058_denominator,v058_cilow,v058_cihigh
1,00,000,00000,US,United States,2022,NaN,7281.9355638,4125218,917267406,...,0.5075447019,167227921,329484123,NaN,NaN,0.1926902892,NaN,NaN,NaN,NaN
2,01,000,01000,AL,Alabama,2022,NaN,10350.071456,88086,13668498,...,0.5170272184,2544566,4921532,NaN,NaN,0.409631829,1957932,4779736,NaN,NaN
3,01,001,01001,AL,Autauga County,2022,1,8027.3947267,836,156081,...,0.5150770327,28919,56145,NaN,NaN,0.4200216232,22921,54571,NaN,NaN
4,01,003,01003,AL,Baldwin County,2022,1,8118.3582061,3377,614143,...,0.5158905651,118287,229287,NaN,NaN,0.4227909911,77060,182265,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2022,1.0,8419.275418,599,122399,...,0.483608,20637,42673,NaN,NaN,0.109163,4782,43806,NaN,NaN
3191,56,39,56039,WY,Teton County,2022,1.0,3283.066198,111,66036,...,0.481338,11310,23497,NaN,NaN,0.464309,9887,21294,NaN,NaN
3192,56,41,56041,WY,Uinta County,2022,1.0,9358.208153,287,57690,...,0.49394,9985,20215,NaN,NaN,0.430959,9101,21118,NaN,NaN
3193,56,43,56043,WY,Washakie County,2022,1.0,7073.941804,115,21075,...,0.490464,3806,7760,NaN,NaN,0.359545,3068,8533,NaN,NaN
3194,56,45,56045,WY,Weston County,2022,1.0,5149.435226,75,18783,...,0.475308,3205,6743,NaN,NaN,0.545366,3931,7208,NaN,NaN

In [4]:
country_df = health_df[health_df['Name'] == "United States"]
country_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% female raw value,% female numerator,% female denominator,% female CI low,% female CI high,% rural raw value,% rural numerator,% rural denominator,% rural CI low,% rural CI high
1,00,000,00000,US,United States,2022,NaN,7281.9355638,4125218,917267406,...,0.5075447019,167227921,329484123,NaN,NaN,0.1926902892,NaN,NaN,NaN,NaN

In [5]:
state_df = health_df[health_df['County FIPS Code'] == "000"]
state_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% female raw value,% female numerator,% female denominator,% female CI low,% female CI high,% rural raw value,% rural numerator,% rural denominator,% rural CI low,% rural CI high
1,00,000,00000,US,United States,2022,NaN,7281.9355638,4125218,917267406,...,0.5075447019,167227921,329484123,NaN,NaN,0.1926902892,NaN,NaN,NaN,NaN
2,01,000,01000,AL,Alabama,2022,NaN,10350.071456,88086,13668498,...,0.5170272184,2544566,4921532,NaN,NaN,0.409631829,1957932,4779736,NaN,NaN
70,02,000,02000,AK,Alaska,2022,NaN,8269.1433549,8663,2109679,...,0.4781743481,349621,731158,NaN,NaN,0.3398021207,241338,710231,NaN,NaN
100,04,000,04000,AZ,Arizona,2022,NaN,7745.3275728,90822,20195672,...,0.5033382511,3735475,7421401,NaN,NaN,0.1019017941,651358,6392017,NaN,NaN
116,05,000,05000,AR,Arkansas,2022,NaN,9749.6704183,50906,8399465,...,0.5093729727,1543666,3030522,NaN,NaN,0.4383967588,1278329,2915918,NaN,NaN
192,06,000,06000,CA,California,2022,NaN,5678.8169503,378883,111095669,...,0.5027065075,19790589,39368078,NaN,NaN,0.0504738342,1880350,37253956,NaN,NaN
251,08,000,08000,CO,Colorado,2022,NaN,6322.5282656,58091,16301283,...,0.4962072029,2881832,5807719,NaN,NaN,0.1384783969,696435,5029196,NaN,NaN
316,09,000,09000,CT,Connecticut,2022,NaN,6106.5059639,38493,9863750,...,0.5122527204,1822086,3557006,NaN,NaN,0.1200736857,429155,3574097,NaN,NaN
325,10,000,10000,DE,Delaware,2022,NaN,8148.5337288,13471,2699672,...,0.5168872598,510069,986809,NaN,NaN,0.1670334345,149985,897934,NaN,NaN
329,11,000,11000,DC,District of Columbia,2022,NaN,8357.205141,8978,2009421,...,0.5259197324,374884,712816,NaN,NaN,0,0,601723,NaN,NaN
331,12,000,12000,FL,Florida,2022,NaN,7478.1007389,282304,58419719,...,0.5113409314,11113132,21733312,NaN,NaN,0.0883696934,1661466,18801310,NaN,NaN
399,13,000,13000,GA,Georgia,2022,NaN,8016.7309458,143179,30075569,...,0.5143285954,5508468,10710017,NaN,NaN,0.249338204,2415502,9687653,NaN,NaN
559,15,000,15000,HI,Hawaii,2022,NaN,5895.0856871,14779,3894605,...,0.4993866409,702640,1407006,NaN,NaN,0.080726251,109812,1360301,NaN,NaN
565,16,000,16000,ID,Idaho,2022,NaN,6327.9658708,19254,5023289,...,0.4985398867,910789,1826913,NaN,NaN,0.2942187394,461212,1567582,NaN,NaN
610,17,000,17000,IL,Illinois,2022,NaN,7066.1812438,155530,35405031,...,0.5086163846,6402224,12587530,NaN,NaN,0.1151212972,1477079,12830632,NaN,NaN
713,18,000,18000,IN,Indiana,2022,NaN,8594.8163642,97951,18834201,...,0.5067383889,3422994,6754953,NaN,NaN,0.2755639361,1786702,6483802,NaN,NaN
806,19,000,19000,IA,Iowa,2022,NaN,6549.1160477,38226,8751525,...,0.5019236234,1587866,3163561,NaN,NaN,0.3598067198,1096099,3046355,NaN,NaN
906,20,000,20000,KS,Kansas,2022,NaN,7457.9724964,37334,8130131,...,0.5018403771,1462265,2913805,NaN,NaN,0.2580184205,736157,2853118,NaN,NaN
1012,21,000,21000,KY,Kentucky,2022,NaN,9992.903252,78388,12506744,...,0.5074332442,2271906,4477251,NaN,NaN,0.4161952653,1806024,4339367,NaN,NaN

In [6]:
county_df = health_df[health_df['County FIPS Code'] != "000"]
county_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% female raw value,% female numerator,% female denominator,% female CI low,% female CI high,% rural raw value,% rural numerator,% rural denominator,% rural CI low,% rural CI high
0,statecode,countycode,fipscode,state,county,year,county_ranked,v001_rawvalue,v001_numerator,v001_denominator,...,v057_rawvalue,v057_numerator,v057_denominator,v057_cilow,v057_cihigh,v058_rawvalue,v058_numerator,v058_denominator,v058_cilow,v058_cihigh
3,01,001,01001,AL,Autauga County,2022,1,8027.3947267,836,156081,...,0.5150770327,28919,56145,NaN,NaN,0.4200216232,22921,54571,NaN,NaN
4,01,003,01003,AL,Baldwin County,2022,1,8118.3582061,3377,614143,...,0.5158905651,118287,229287,NaN,NaN,0.4227909911,77060,182265,NaN,NaN
5,01,005,01005,AL,Barbour County,2022,1,12876.760319,539,68126,...,0.4718370003,11602,24589,NaN,NaN,0.677896347,18613,27457,NaN,NaN
6,01,007,01007,AL,Bibb County,2022,1,11191.474323,460,62304,...,0.4681514275,10363,22136,NaN,NaN,0.6835260746,15663,22915,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2022,1.0,8419.275418,599,122399,...,0.483608,20637,42673,NaN,NaN,0.109163,4782,43806,NaN,NaN
3191,56,39,56039,WY,Teton County,2022,1.0,3283.066198,111,66036,...,0.481338,11310,23497,NaN,NaN,0.464309,9887,21294,NaN,NaN
3192,56,41,56041,WY,Uinta County,2022,1.0,9358.208153,287,57690,...,0.49394,9985,20215,NaN,NaN,0.430959,9101,21118,NaN,NaN
3193,56,43,56043,WY,Washakie County,2022,1.0,7073.941804,115,21075,...,0.490464,3806,7760,NaN,NaN,0.359545,3068,8533,NaN,NaN
3194,56,45,56045,WY,Weston County,2022,1.0,5149.435226,75,18783,...,0.475308,3205,6743,NaN,NaN,0.545366,3931,7208,NaN,NaN

In [7]:
county_df = county_df.loc[1:]
county_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% female raw value,% female numerator,% female denominator,% female CI low,% female CI high,% rural raw value,% rural numerator,% rural denominator,% rural CI low,% rural CI high
3,01,001,01001,AL,Autauga County,2022,1,8027.3947267,836,156081,...,0.5150770327,28919,56145,NaN,NaN,0.4200216232,22921,54571,NaN,NaN
4,01,003,01003,AL,Baldwin County,2022,1,8118.3582061,3377,614143,...,0.5158905651,118287,229287,NaN,NaN,0.4227909911,77060,182265,NaN,NaN
5,01,005,01005,AL,Barbour County,2022,1,12876.760319,539,68126,...,0.4718370003,11602,24589,NaN,NaN,0.677896347,18613,27457,NaN,NaN
6,01,007,01007,AL,Bibb County,2022,1,11191.474323,460,62304,...,0.4681514275,10363,22136,NaN,NaN,0.6835260746,15663,22915,NaN,NaN
7,01,009,01009,AL,Blount County,2022,1,10787.014541,1143,160188,...,0.5055719691,29262,57879,NaN,NaN,0.8995150204,51562,57322,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2022,1.0,8419.275418,599,122399,...,0.483608,20637,42673,NaN,NaN,0.109163,4782,43806,NaN,NaN
3191,56,39,56039,WY,Teton County,2022,1.0,3283.066198,111,66036,...,0.481338,11310,23497,NaN,NaN,0.464309,9887,21294,NaN,NaN
3192,56,41,56041,WY,Uinta County,2022,1.0,9358.208153,287,57690,...,0.49394,9985,20215,NaN,NaN,0.430959,9101,21118,NaN,NaN
3193,56,43,56043,WY,Washakie County,2022,1.0,7073.941804,115,21075,...,0.490464,3806,7760,NaN,NaN,0.359545,3068,8533,NaN,NaN
3194,56,45,56045,WY,Weston County,2022,1.0,5149.435226,75,18783,...,0.475308,3205,6743,NaN,NaN,0.545366,3931,7208,NaN,NaN

In [8]:
county_df.columns

Index(['State FIPS Code', 'County FIPS Code', '5-digit FIPS Code',
       'State Abbreviation', 'Name', 'Release Year',
       'County Ranked (Yes=1/No=0)', 'Premature death raw value',
       'Premature death numerator', 'Premature death denominator',
       ...
       '% female raw value', '% female numerator', '% female denominator',
       '% female CI low', '% female CI high', '% rural raw value',
       '% rural numerator', '% rural denominator', '% rural CI low',
       '% rural CI high'],
      dtype='object', length=725)

In [9]:
county_df.isnull().sum()

State FIPS Code           0
County FIPS Code          0
5-digit FIPS Code         0
State Abbreviation        0
Name                      0
                       ...
% rural raw value         7
% rural numerator         7
% rural denominator       7
% rural CI low         3175
% rural CI high        3175
Length: 725, dtype: int64

In [10]:
pct_null = county_df.isnull().sum()/len(county_df)
missing_features = pct_null[pct_null > 0.80].index
county_df.drop(missing_features, axis=1, inplace=True)
county_df

/var/folders/fx/3xjkq6_j0w52ql5m_lv0vsbr0000gn/T/ipykernel_2354/3348728470.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  county_df.drop(missing_features, axis=1, inplace=True)

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,Release Year,County Ranked (Yes=1/No=0),Premature death raw value,Premature death numerator,Premature death denominator,...,% not proficient in English numerator,% not proficient in English denominator,% not proficient in English CI low,% not proficient in English CI high,% female raw value,% female numerator,% female denominator,% rural raw value,% rural numerator,% rural denominator
3,01,001,01001,AL,Autauga County,2022,1,8027.3947267,836,156081,...,363,52404,0.0017010086,0.0121528956,0.5150770327,28919,56145,0.4200216232,22921,54571
4,01,003,01003,AL,Baldwin County,2022,1,8118.3582061,3377,614143,...,1593,206329,0.0049126531,0.0105287051,0.5158905651,118287,229287,0.4227909911,77060,182265
5,01,005,01005,AL,Barbour County,2022,1,12876.760319,539,68126,...,433,23694,0.0079502598,0.0285990776,0.4718370003,11602,24589,0.677896347,18613,27457
6,01,007,01007,AL,Bibb County,2022,1,11191.474323,460,62304,...,75,21121,0,0.0096285112,0.4681514275,10363,22136,0.6835260746,15663,22915
7,01,009,01009,AL,Blount County,2022,1,10787.014541,1143,160188,...,801,54250,0.0089873018,0.0205426521,0.5055719691,29262,57879,0.8995150204,51562,57322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,2022,1.0,8419.275418,599,122399,...,321,40482,0.002901,0.012958,0.483608,20637,42673,0.109163,4782,43806
3191,56,39,56039,WY,Teton County,2022,1.0,3283.066198,111,66036,...,668,22310,0.014451,0.045433,0.481338,11310,23497,0.464309,9887,21294
3192,56,41,56041,WY,Uinta County,2022,1.0,9358.208153,287,57690,...,237,18910,0.001921,0.023145,0.49394,9985,20215,0.430959,9101,21118
3193,56,43,56043,WY,Washakie County,2022,1.0,7073.941804,115,21075,...,16,7491,0.0,0.012753,0.490464,3806,7760,0.359545,3068,8533
3194,56,45,56045,WY,Weston County,2022,1.0,5149.435226,75,18783,...,13,6598,0.0,0.013996,0.475308,3205,6743,0.545366,3931,7208

In [11]:
column_list = county_df.columns.values.tolist()
column_list

['State FIPS Code',
 'County FIPS Code',
 '5-digit FIPS Code',
 'State Abbreviation',
 'Name',
 'Release Year',
 'County Ranked (Yes=1/No=0)',
 'Premature death raw value',
 'Premature death numerator',
 'Premature death denominator',
 'Premature death CI low',
 'Premature death CI high',
 'Premature death flag (0 = No Flag/1=Unreliable/2=Suppressed)',
 'Premature death flag (AIAN) (. = No Flag/1=Unreliable/2=Suppressed)',
 'Premature death flag (Asian/Pacific Islander) (. = No Flag/1=Unreliable/2=Suppressed)',
 'Premature death (Black)',
 'Premature death CI low (Black)',
 'Premature death CI high (Black)',
 'Premature death flag (Black) (. = No Flag/1=Unreliable/2=Suppressed)',
 'Premature death (Hispanic)',
 'Premature death CI low (Hispanic)',
 'Premature death CI high (Hispanic)',
 'Premature death flag (Hispanic) (. = No Flag/1=Unreliable/2=Suppressed)',
 'Premature death (White)',
 'Premature death CI low (White)',
 'Premature death CI high (White)',
 'Poor or fair health raw value',
 'Poor or fair health CI low',
 'Poor or fair health CI high',
 'Poor physical health days raw value',
 'Poor physical health days CI low',
 'Poor physical health days CI high',
 'Poor mental health days raw value',
 'Poor mental health days CI low',
 'Poor mental health days CI high',
 'Low birthweight raw value',
 'Low birthweight numerator',
 'Low birthweight denominator',
 'Low birthweight CI low',
 'Low birthweight CI high',
 'LBW unreliable indicator (Unreliable = Numerator < 20 or relative standard error > 20%)',
 'Low birthweight (Asian/Pacific Islander)',
 'Low birthweight CI low (Asian/Pacific Islander)',
 'Low birthweight CI high (Asian/Pacific Islander)',
 'Low birthweight (Black)',
 'Low birthweight CI low (Black)',
 'Low birthweight CI high (Black)',
 'Low birthweight (Hispanic)',
 'Low birthweight CI low (Hispanic)',
 'Low birthweight CI high (Hispanic)',
 'Low birthweight (White)',
 'Low birthweight CI low (White)',
 'Low birthweight CI high (White)',
 'Adult smoking raw value',
 'Adult smoking CI low',
 'Adult smoking CI high',
 'Adult obesity raw value',
 'Adult obesity CI low',
 'Adult obesity CI high',
 'Food environment index raw value',
 'Food environment index numerator',
 'Food environment index denominator',
 'Physical inactivity raw value',
 'Physical inactivity CI low',
 'Physical inactivity CI high',
 'Access to exercise opportunities raw value',
 'Access to exercise opportunities numerator',
 'Access to exercise opportunities denominator',
 'Excessive drinking raw value',
 'Excessive drinking CI low',
 'Excessive drinking CI high',
 'Alcohol-impaired driving deaths raw value',
 'Alcohol-impaired driving deaths numerator',
 'Alcohol-impaired driving deaths denominator',
 'Alcohol-impaired driving deaths CI low',
 'Alcohol-impaired driving deaths CI high',
 'Sexually transmitted infections raw value',
 'Sexually transmitted infections numerator',
 'Sexually transmitted infections denominator',
 'Teen births raw value',
 'Teen births numerator',
 'Teen births denominator',
 'Teen births CI low',
 'Teen births CI high',
 'Teen births (Black)',
 'Teen births CI low (Black)',
 'Teen births CI high (Black)',
 'Teen births (Hispanic)',
 'Teen births CI low (Hispanic)',
 'Teen births CI high (Hispanic)',
 'Teen births (White)',
 'Teen births CI low (White)',
 'Teen births CI high (White)',
 'Uninsured raw value',
 'Uninsured numerator',
 'Uninsured denominator',
 'Uninsured CI low',
 'Uninsured CI high',
 'Primary care physicians raw value',
 'Primary care physicians numerator',
 'Primary care physicians denominator',
 'Ratio of population to primary care physicians.',
 'Dentists raw value',
 'Dentists numerator',
 'Dentists denominator',
 'Ratio of population to dentists.',
 'Mental health providers raw value',
 'Mental health providers numerator',
 'Mental health providers denominator',
 'Ratio of population to mental health providers.',
 'Preventable hospital stays raw value',
 'Preventable hospital stays (Black)',
 'Preventable hospital stays (Hispanic)',
 'Preventable hospital stays (White)',
 'Mammography screening raw value',
 'Mammography screening (Asian/Pacific Islander)',
 'Mammography screening (Black)',
 'Mammography screening (Hispanic)',
 'Mammography screening (White)',
 'Flu vaccinations raw value',
 'Flu vaccinations (AIAN)',
 'Flu vaccinations (Asian/Pacific Islander)',
 'Flu vaccinations (Black)',
 'Flu vaccinations (Hispanic)',
 'Flu vaccinations (White)',
 'High school completion raw value',
 'High school completion numerator',
 'High school completion denominator',
 'High school completion CI low',
 'High school completion CI high',
 'Some college raw value',
 'Some college numerator',
 'Some college denominator',
 'Some college CI low',
 'Some college CI high',
 'Unemployment raw value',
 'Unemployment numerator',
 'Unemployment denominator',
 'Children in poverty raw value',
 'Children in poverty numerator',
 'Children in poverty CI low',
 'Children in poverty CI high',
 'Children in poverty (AIAN)',
 'Children in poverty CI low (AIAN)',
 'Children in poverty CI high (AIAN)',
 'Children in poverty (Asian/Pacific Islander)',
 'Children in poverty CI low (Asian/Pacific Islander)',
 'Children in poverty CI high (Asian/Pacific Islander)',
 'Children in poverty (Black)',
 'Children in poverty CI low (Black)',
 'Children in poverty CI high (Black)',
 'Children in poverty (Hispanic)',
 'Children in poverty CI low (Hispanic)',
 'Children in poverty CI high (Hispanic)',
 'Children in poverty (White)',
 'Children in poverty CI low (White)',
 'Children in poverty CI high (White)',
 'Income inequality raw value',
 'Income inequality numerator',
 'Income inequality denominator',
 'Income inequality CI low',
 'Income inequality CI high',
 'Children in single-parent households raw value',
 'Children in single-parent households numerator',
 'Children in single-parent households denominator',
 'Children in single-parent households CI low',
 'Children in single-parent households CI high',
 'Social associations raw value',
 'Social associations numerator',
 'Social associations denominator',
 'Violent crime raw value',
 'Violent crime numerator',
 'Violent crime denominator',
 'Injury deaths raw value',
 'Injury deaths numerator',
 'Injury deaths denominator',
 'Injury deaths CI low',
 'Injury deaths CI high',
 'Injury deaths (Black)',
 'Injury deaths CI low (Black)',
 'Injury deaths CI high (Black)',
 'Injury deaths (Hispanic)',
 'Injury deaths CI low (Hispanic)',
 'Injury deaths CI high (Hispanic)',
 'Injury deaths (White)',
 'Injury deaths CI low (White)',
 'Injury deaths CI high (White)',
 'Air pollution - particulate matter raw value',
 'Drinking water violations raw value',
 'Severe housing problems raw value',
 'Severe housing problems numerator',
 'Severe housing problems denominator',
 'Severe housing problems CI low',
 'Severe housing problems CI high',
 'Percentage of households with high housing costs',
 'Percentage of households with high housing costs CI low',
 'Percentage of households with high housing costs CI high',
 'Percentage of households with overcrowding',
 'Percentage of households with overcrowding CI low',
 'Percentage of households with overcrowding CI high',
 'Percentage of households with lack of kitchen or plumbing facilities',
 'Percentage of households with lack of kitchen or plumbing facilities CI low',
 'Percentage of households with lack of kitchen or plumbing facilities CI high',
 'Driving alone to work raw value',
 'Driving alone to work numerator',
 'Driving alone to work denominator',
 'Driving alone to work CI low',
 'Driving alone to work CI high',
 'Driving alone to work (Black)',
 'Driving alone to work CI low (Black)',
 'Driving alone to work CI high (Black)',
 'Driving alone to work (Hispanic)',
 'Driving alone to work CI low (Hispanic)',
 'Driving alone to work CI high (Hispanic)',
 'Driving alone to work (White)',
 'Driving alone to work CI low (White)',
 'Driving alone to work CI high (White)',
 'Long commute - driving alone raw value',
 'Long commute - driving alone denominator',
 'Long commute - driving alone CI low',
 'Long commute - driving alone CI high',
 'COVID-19 age-adjusted mortality raw value',
 'COVID-19 age-adjusted mortality numerator',
 'COVID-19 age-adjusted mortality denominator',
 'COVID-19 age-adjusted mortality CI low',
 'COVID-19 age-adjusted mortality CI high',
 'Life expectancy raw value',
 'Life expectancy CI low',
 'Life expectancy CI high',
 'Life expectancy (Black)',
 'Life expectancy CI low (Black)',
 'Life expectancy CI high (Black)',
 'Life expectancy (Hispanic)',
 'Life expectancy CI low (Hispanic)',
 'Life expectancy CI high (Hispanic)',
 'Life expectancy (White)',
 'Life expectancy CI low (White)',
 'Life expectancy CI high (White)',
 'Premature age-adjusted mortality raw value',
 'Premature age-adjusted mortality numerator',
 'Premature age-adjusted mortality denominator',
 'Premature age-adjusted mortality CI low',
 'Premature age-adjusted mortality CI high',
 'Premature age-adjusted mortality (Black)',
 'Premature age-adjusted mortality CI low (Black)',
 'Premature age-adjusted mortality CI high (Black)',
 'Premature age-adjusted mortality (Hispanic)',
 'Premature age-adjusted mortality CI low (Hispanic)',
 'Premature age-adjusted mortality CI high (Hispanic)',
 'Premature age-adjusted mortality (White)',
 'Premature age-adjusted mortality CI low (White)',
 'Premature age-adjusted mortality CI high (White)',
 'Child mortality raw value',
 'Child mortality numerator',
 'Child mortality denominator',
 'Child mortality CI low',
 'Child mortality CI high',
 'Child mortality (White)',
 'Child mortality CI low (White)',
 'Child mortality CI high (White)',
 'Infant mortality raw value',
 'Infant mortality numerator',
 'Infant mortality denominator',
 'Infant mortality CI low',
 'Infant mortality CI high',
 'Infant mortality (White)',
 'Infant mortality CI low (White)',
 'Infant mortality CI high (White)',
 'Frequent physical distress raw value',
 'Frequent physical distress CI low',
 'Frequent physical distress CI high',
 'Frequent mental distress raw value',
 'Frequent mental distress CI low',
 'Frequent mental distress CI high',
 'Diabetes prevalence raw value',
 'Diabetes prevalence CI low',
 'Diabetes prevalence CI high',
 'HIV prevalence raw value',
 'HIV prevalence numerator',
 'HIV prevalence denominator',
 'Food insecurity raw value',
 'Food insecurity numerator',
 'Limited access to healthy foods raw value',
 'Limited access to healthy foods numerator',
 'Limited access to healthy foods denominator',
 'Drug overdose deaths raw value',
 'Drug overdose deaths numerator',
 'Drug overdose deaths denominator',
 'Drug overdose deaths CI low',
 'Drug overdose deaths CI high',
 'Drug overdose deaths (White)',
 'Drug overdose deaths CI low (White)',
 'Drug overdose deaths CI high (White)',
 'Motor vehicle crash deaths raw value',
 'Motor vehicle crash deaths numerator',
 'Motor vehicle crash deaths denominator',
 'Motor vehicle crash deaths CI low',
 'Motor vehicle crash deaths CI high',
 'Motor vehicle crash deaths (Black)',
 'Motor vehicle crash deaths CI low (Black)',
 'Motor vehicle crash deaths CI high (Black)',
 'Motor vehicle crash deaths (White)',
 'Motor vehicle crash deaths CI low (White)',
 'Motor vehicle crash deaths CI high (White)',
 'Insufficient sleep raw value',
 'Insufficient sleep CI low',
 'Insufficient sleep CI high',
 'Uninsured adults raw value',
 'Uninsured adults numerator',
 'Uninsured adults denominator',
 'Uninsured adults CI low',
 'Uninsured adults CI high',
 'Uninsured children raw value',
 'Uninsured children numerator',
 'Uninsured children denominator',
 'Uninsured children CI low',
 'Uninsured children CI high',
 'Other primary care providers raw value',
 'Other primary care providers numerator',
 'Other primary care providers denominator',
 'Ratio of population to primary care providers other than physicians.',
 'High school graduation raw value',
 'High school graduation numerator',
 'High school graduation denominator',
 'Disconnected youth raw value',
 'Disconnected youth numerator',
 'Disconnected youth denominator',
 'Disconnected youth CI low',
 'Disconnected youth CI high',
 'Reading scores raw value',
 'Reading scores (Black)',
 'Reading scores (Hispanic)',
 'Reading scores (White)',
 'Math scores raw value',
 'Math scores (Black)',
 'Math scores (Hispanic)',
 'Math scores (White)',
 'School segregation raw value',
 'School funding adequacy raw value',
 'Gender pay gap raw value',
 'Gender pay gap numerator',
 'Gender pay gap denominator',
 'Gender pay gap CI low',
 'Gender pay gap CI high',
 'Median household income raw value',
 'Median household income CI low',
 'Median household income CI high',
 'Median household income (AIAN)',
 'Median household income CI low (AIAN)',
 'Median household income CI high (AIAN)',
 'Median household income (Asian)',
 'Median household income CI low (Asian)',
 'Median household income CI high (Asian)',
 'Median household income (Black)',
 'Median household income CI low (Black)',
 'Median household income CI high (Black)',
 'Median household income (Hispanic)',
 'Median household income CI low (Hispanic)',
 'Median household income CI high (Hispanic)',
 'Median household income (White)',
 'Median household income CI low (White)',
 'Median household income CI high (White)',
 'Children eligible for free or reduced price lunch raw value',
 'Children eligible for free or reduced price lunch numerator',
 'Children eligible for free or reduced price lunch denominator',
 'Residential segregation - Black/white raw value',
 'Residential segregation - non-white/white raw value',
 'Childcare cost burden raw value',
 'Childcare cost burden denominator',
 'Childcare centers raw value',
 'Childcare centers numerator',
 'Childcare centers denominator',
 'Homicides raw value',
 'Homicides numerator',
 'Homicides denominator',
 'Homicides CI low',
 'Homicides CI high',
 'Homicides (Black)',
 'Homicides CI low (Black)',
 'Homicides CI high (Black)',
 'Homicides (White)',
 'Homicides CI low (White)',
 'Homicides CI high (White)',
 'Suicides raw value',
 'Suicides numerator',
 'Suicides denominator',
 'Suicides CI low',
 'Suicides CI high',
 'Crude suicide rate',
 'Suicides (White)',
 'Suicides CI low (White)',
 'Suicides CI high (White)',
 'Firearm fatalities raw value',
 'Firearm fatalities numerator',
 'Firearm fatalities denominator',
 'Firearm fatalities CI low',
 'Firearm fatalities CI high',
 'Firearm fatalities (White)',
 'Firearm fatalities CI low (White)',
 'Firearm fatalities CI high (White)',
 'Juvenile arrests raw value',
 'Juvenile arrests denominator',
 'Number of juvenile delinquency cases formally processed by a juvenile court',
 'Number of informally handled juvenile delinquency cases',
 'Traffic volume raw value',
 'Homeownership raw value',
 'Homeownership numerator',
 'Homeownership denominator',
 'Homeownership CI low',
 'Homeownership CI high',
 'Severe housing cost burden raw value',
 'Severe housing cost burden numerator',
 'Severe housing cost burden denominator',
 'Severe housing cost burden CI low',
 'Severe housing cost burden CI high',
 'Broadband access raw value',
 'Broadband access numerator',
 'Broadband access denominator',
 'Broadband access CI low',
 'Broadband access CI high',
 'Population raw value',
 '% below 18 years of age raw value',
 '% below 18 years of age numerator',
 '% below 18 years of age denominator',
 '% 65 and older raw value',
 '% 65 and older numerator',
 '% 65 and older denominator',
 '% non-Hispanic Black raw value',
 '% non-Hispanic Black numerator',
 '% non-Hispanic Black denominator',
 '% American Indian & Alaska Native raw value',
 '% American Indian & Alaska Native numerator',
 '% American Indian & Alaska Native denominator',
 '% Asian raw value',
 '% Asian numerator',
 '% Asian denominator',
 '% Native Hawaiian/Other Pacific Islander raw value',
 '% Native Hawaiian/Other Pacific Islander numerator',
 '% Native Hawaiian/Other Pacific Islander denominator',
 '% Hispanic raw value',
 '% Hispanic numerator',
 '% Hispanic denominator',
 '% non-Hispanic white raw value',
 '% non-Hispanic white numerator',
 '% non-Hispanic white denominator',
 '% not proficient in English raw value',
 '% not proficient in English numerator',
 '% not proficient in English denominator',
 '% not proficient in English CI low',
 '% not proficient in English CI high',
 '% female raw value',
 '% female numerator',
 '% female denominator',
 '% rural raw value',
 '% rural numerator',
 '% rural denominator']

In [12]:
def raw_value(list):
    raw_value_list = []
    for column in list:
        column_split = column.split()
        if column_split[-1] == "value": # and column_split[-2] == "raw"
            raw_value_list.append(column)
        if column_split[-1] != "value":
            continue
    return print(raw_value_list)
raw_value_list = raw_value(column_list)
print(raw_value_list)

['Premature death raw value', 'Poor or fair health raw value', 'Poor physical health days raw value', 'Poor mental health days raw value', 'Low birthweight raw value', 'Adult smoking raw value', 'Adult obesity raw value', 'Food environment index raw value', 'Physical inactivity raw value', 'Access to exercise opportunities raw value', 'Excessive drinking raw value', 'Alcohol-impaired driving deaths raw value', 'Sexually transmitted infections raw value', 'Teen births raw value', 'Uninsured raw value', 'Primary care physicians raw value', 'Dentists raw value', 'Mental health providers raw value', 'Preventable hospital stays raw value', 'Mammography screening raw value', 'Flu vaccinations raw value', 'High school completion raw value', 'Some college raw value', 'Unemployment raw value', 'Children in poverty raw value', 'Income inequality raw value', 'Children in single-parent households raw value', 'Social associations raw value', 'Violent crime raw value', 'Injury deaths raw value', 'Air pollution - particulate matter raw value', 'Drinking water violations raw value', 'Severe housing problems raw value', 'Driving alone to work raw value', 'Long commute - driving alone raw value', 'COVID-19 age-adjusted mortality raw value', 'Life expectancy raw value', 'Premature age-adjusted mortality raw value', 'Child mortality raw value', 'Infant mortality raw value', 'Frequent physical distress raw value', 'Frequent mental distress raw value', 'Diabetes prevalence raw value', 'HIV prevalence raw value', 'Food insecurity raw value', 'Limited access to healthy foods raw value', 'Drug overdose deaths raw value', 'Motor vehicle crash deaths raw value', 'Insufficient sleep raw value', 'Uninsured adults raw value', 'Uninsured children raw value', 'Other primary care providers raw value', 'High school graduation raw value', 'Disconnected youth raw value', 'Reading scores raw value', 'Math scores raw value', 'School segregation raw value', 'School funding adequacy raw value', 'Gender pay gap raw value', 'Median household income raw value', 'Children eligible for free or reduced price lunch raw value', 'Residential segregation - Black/white raw value', 'Residential segregation - non-white/white raw value', 'Childcare cost burden raw value', 'Childcare centers raw value', 'Homicides raw value', 'Suicides raw value', 'Firearm fatalities raw value', 'Juvenile arrests raw value', 'Traffic volume raw value', 'Homeownership raw value', 'Severe housing cost burden raw value', 'Broadband access raw value', 'Population raw value', '% below 18 years of age raw value', '% 65 and older raw value', '% non-Hispanic Black raw value', '% American Indian & Alaska Native raw value', '% Asian raw value', '% Native Hawaiian/Other Pacific Islander raw value', '% Hispanic raw value', '% non-Hispanic white raw value', '% not proficient in English raw value', '% female raw value', '% rural raw value']
None

In [13]:
# cols = pd.Series(raw_value_list)

In [14]:
# cols = raw_value_list
# raw_value_df = county_df[cols]
# raw_value_df

In [15]:
# for x in raw_value_list:
#     raw_value_df.append(county_df[x])

In [16]:
raw_value_df = county_df[['Premature death raw value', 'Poor or fair health raw value', 'Poor physical health days raw value', 
'Poor mental health days raw value', 'Low birthweight raw value', 'Adult smoking raw value', 'Adult obesity raw value', 
'Food environment index raw value', 'Physical inactivity raw value', 'Access to exercise opportunities raw value', 
'Excessive drinking raw value', 'Alcohol-impaired driving deaths raw value', 'Sexually transmitted infections raw value', 
'Teen births raw value', 'Uninsured raw value', 'Primary care physicians raw value', 'Dentists raw value', 
'Mental health providers raw value', 'Preventable hospital stays raw value', 'Mammography screening raw value', 
'Flu vaccinations raw value', 'High school completion raw value', 'Some college raw value', 'Unemployment raw value', 
'Children in poverty raw value', 'Income inequality raw value', 'Children in single-parent households raw value', 
'Social associations raw value', 'Violent crime raw value', 'Injury deaths raw value', 'Air pollution - particulate matter raw value', 
'Drinking water violations raw value', 'Severe housing problems raw value', 'Driving alone to work raw value', 
'Long commute - driving alone raw value', 'COVID-19 age-adjusted mortality raw value', 'Life expectancy raw value', 
'Premature age-adjusted mortality raw value', 'Child mortality raw value', 'Infant mortality raw value', 
'Frequent physical distress raw value', 'Frequent mental distress raw value', 'Diabetes prevalence raw value', 
'HIV prevalence raw value', 'Food insecurity raw value', 'Limited access to healthy foods raw value', 
'Drug overdose deaths raw value', 'Motor vehicle crash deaths raw value', 'Insufficient sleep raw value', 
'Uninsured adults raw value', 'Uninsured children raw value', 'Other primary care providers raw value', 
'High school graduation raw value', 'Disconnected youth raw value', 'Reading scores raw value', 'Math scores raw value', 
'School segregation raw value', 'School funding adequacy raw value', 'Gender pay gap raw value', 'Median household income raw value', 
'Children eligible for free or reduced price lunch raw value', 'Residential segregation - Black/white raw value', 
'Residential segregation - non-white/white raw value', 'Childcare cost burden raw value', 'Childcare centers raw value', 
'Homicides raw value', 'Suicides raw value', 'Firearm fatalities raw value', 'Juvenile arrests raw value', 
'Traffic volume raw value', 'Homeownership raw value', 'Severe housing cost burden raw value', 'Broadband access raw value', 
'Population raw value', '% below 18 years of age raw value', '% 65 and older raw value', '% non-Hispanic Black raw value', 
'% American Indian & Alaska Native raw value', '% Asian raw value', '% Native Hawaiian/Other Pacific Islander raw value', 
'% Hispanic raw value', '% non-Hispanic white raw value', '% not proficient in English raw value', '% female raw value', '% rural raw value']]
raw_value_df

,Premature death raw value,Poor or fair health raw value,Poor physical health days raw value,Poor mental health days raw value,Low birthweight raw value,Adult smoking raw value,Adult obesity raw value,Food environment index raw value,Physical inactivity raw value,Access to exercise opportunities raw value,...,% 65 and older raw value,% non-Hispanic Black raw value,% American Indian & Alaska Native raw value,% Asian raw value,% Native Hawaiian/Other Pacific Islander raw value,% Hispanic raw value,% non-Hispanic white raw value,% not proficient in English raw value,% female raw value,% rural raw value
3,8027.3947267,0.201,4.5100424038,5.4190677155,0.0973815192,0.197,0.353,6.5,0.322,0.6275860805,...,0.1617597293,0.2031881735,0.0047377327,0.0117018434,0.0010864725,0.0310089946,0.731659097,0.0069269521,0.5150770327,0.4200216232
4,8118.3582061,0.172,4.168866136,5.173915124,0.0838573118,0.199,0.296,7.4,0.276,0.745079966,...,0.2158212197,0.0847889326,0.0077980871,0.0110298447,0.0006629246,0.046339304,0.8330825559,0.0077206791,0.5158905651,0.4227909911
5,12876.760319,0.311,5.8844146337,6.1098993294,0.1191467222,0.278,0.404,5.7,0.416,0.498379284,...,0.2026109236,0.4780999634,0.0069949978,0.0045548823,0.0020334296,0.0467282118,0.452641425,0.0182746687,0.4718370003,0.677896347
6,11191.474323,0.25,5.161337369,5.8460957209,0.1003307607,0.252,0.412,7.6,0.377,0.1060440759,...,0.1707625587,0.2097940007,0.0046078786,0.002574991,0.0012197326,0.0293187568,0.741778099,0.0035509682,0.4681514275,0.6835260746
7,10787.014541,0.232,4.9483926568,5.7382383487,0.0785988894,0.222,0.387,7.8,0.333,0.23376714,...,0.1900343821,0.0152732425,0.0062889822,0.0038010332,0.0012094197,0.0954404879,0.8679832063,0.014764977,0.5055719691,0.8995150204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,8419.275418,0.163,3.495993,3.93355,0.101337,0.17,0.335,8.1,0.252,0.830731,...,0.137417,0.010991,0.014482,0.010077,0.001781,0.161882,0.791953,0.007929,0.483608,0.109163
3191,3283.066198,0.116,2.779692,3.305173,0.080655,0.113,0.222,8.7,0.185,0.964967,...,0.165979,0.007363,0.009916,0.015491,0.001787,0.149508,0.810146,0.029942,0.481338,0.464309
3192,9358.208153,0.172,3.792121,4.268578,0.095438,0.188,0.298,8.3,0.278,0.788806,...,0.156567,0.005689,0.016077,0.005293,0.001583,0.099035,0.868068,0.012533,0.49394,0.430959
3193,7073.941804,0.173,3.660729,4.040619,0.067114,0.176,0.289,8.3,0.259,0.76292,...,0.232861,0.00451,0.016753,0.008634,0.000773,0.141624,0.824742,0.002136,0.490464,0.359545
3194,5149.435226,0.16,3.703659,4.180846,0.067982,0.192,0.334,7.6,0.265,0.282325,...,0.224677,0.006822,0.019872,0.014534,0.000297,0.04108,0.900638,0.00197,0.475308,0.545366

In [17]:
raw_value_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3175 entries, 3 to 3194
Data columns (total 85 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   Premature death raw value                                    3115 non-null   object
 1   Poor or fair health raw value                                3175 non-null   object
 2   Poor physical health days raw value                          3175 non-null   object
 3   Poor mental health days raw value                            3175 non-null   object
 4   Low birthweight raw value                                    3069 non-null   object
 5   Adult smoking raw value                                      3175 non-null   object
 6   Adult obesity raw value                                      3175 non-null   object
 7   Food environment index raw value                             3142 non-null   object
 8   Physical inactivity raw value                                3175 non-null   object
 9   Access to exercise opportunities raw value                   3099 non-null   object
 10  Excessive drinking raw value                                 3175 non-null   object
 11  Alcohol-impaired driving deaths raw value                    3148 non-null   object
 12  Sexually transmitted infections raw value                    3057 non-null   object
 13  Teen births raw value                                        2986 non-null   object
 14  Uninsured raw value                                          3174 non-null   object
 15  Primary care physicians raw value                            3022 non-null   object
 16  Dentists raw value                                           3085 non-null   object
 17  Mental health providers raw value                            2971 non-null   object
 18  Preventable hospital stays raw value                         3122 non-null   object
 19  Mammography screening raw value                              3155 non-null   object
 20  Flu vaccinations raw value                                   3156 non-null   object
 21  High school completion raw value                             3175 non-null   object
 22  Some college raw value                                       3175 non-null   object
 23  Unemployment raw value                                       3174 non-null   object
 24  Children in poverty raw value                                3174 non-null   object
 25  Income inequality raw value                                  3169 non-null   object
 26  Children in single-parent households raw value               3174 non-null   object
 27  Social associations raw value                                3175 non-null   object
 28  Violent crime raw value                                      2984 non-null   object
 29  Injury deaths raw value                                      3070 non-null   object
 30  Air pollution - particulate matter raw value                 3148 non-null   object
 31  Drinking water violations raw value                          3132 non-null   object
 32  Severe housing problems raw value                            3175 non-null   object
 33  Driving alone to work raw value                              3174 non-null   object
 34  Long commute - driving alone raw value                       3175 non-null   object
 35  COVID-19 age-adjusted mortality raw value                    2597 non-null   object
 36  Life expectancy raw value                                    3105 non-null   object
 37  Premature age-adjusted mortality raw value                   3115 non-null   object
 38  Child mortality raw value                                    1917 non-null   object
 39  Infant mortality raw value                                   1250 non-null   object
 40  Frequent physical distress raw value                         3175 non-null   object
 41  Frequent mental distress raw value                           3175 non-null   object
 42  Diabetes prevalence raw value                                3175 non-null   object
 43  HIV prevalence raw value                                     2716 non-null   object
 44  Food insecurity raw value                                    3175 non-null   object
 45  Limited access to healthy foods raw value                    3142 non-null   object
 46  Drug overdose deaths raw value                               1830 non-null   object
 47  Motor vehicle crash deaths raw value                         2724 non-null   object
 48  Insufficient sleep raw value                                 3175 non-null   object
 49  Uninsured adults raw value                                   3174 non-null   object
 50  Uninsured children raw value                                 3174 non-null   object
 51  Other primary care providers raw value                       3161 non-null   object
 52  High school graduation raw value                             2516 non-null   object
 53  Disconnected youth raw value                                 1254 non-null   object
 54  Reading scores raw value                                     2809 non-null   object
 55  Math scores raw value                                        2722 non-null   object
 56  School segregation raw value                                 2933 non-null   object
 57  School funding adequacy raw value                            3091 non-null   object
 58  Gender pay gap raw value                                     3171 non-null   object
 59  Median household income raw value                            3173 non-null   object
 60  Children eligible for free or reduced price lunch raw value  3121 non-null   object
 61  Residential segregation - Black/white raw value              2111 non-null   object
 62  Residential segregation - non-white/white raw value          2883 non-null   object
 63  Childcare cost burden raw value                              3173 non-null   object
 64  Childcare centers raw value                                  3002 non-null   object
 65  Homicides raw value                                          1359 non-null   object
 66  Suicides raw value                                           2466 non-null   object
 67  Firearm fatalities raw value                                 2304 non-null   object
 68  Juvenile arrests raw value                                   1985 non-null   object
 69  Traffic volume raw value                                     3175 non-null   object
 70  Homeownership raw value                                      3175 non-null   object
 71  Severe housing cost burden raw value                         3171 non-null   object
 72  Broadband access raw value                                   3175 non-null   object
 73  Population raw value                                         3175 non-null   object
 74  % below 18 years of age raw value                            3175 non-null   object
 75  % 65 and older raw value                                     3175 non-null   object
 76  % non-Hispanic Black raw value                               3175 non-null   object
 77  % American Indian & Alaska Native raw value                  3175 non-null   object
 78  % Asian raw value                                            3175 non-null   object
 79  % Native Hawaiian/Other Pacific Islander raw value           3175 non-null   object
 80  % Hispanic raw value                                         3175 non-null   object
 81  % non-Hispanic white raw value                               3175 non-null   object
 82  % not proficient in English raw value                        3175 non-null   object
 83  % female raw value                                           3175 non-null   object
 84  % rural raw value                                            3168 non-null   object
dtypes: object(85)
memory usage: 2.1+ MB

In [18]:
cols = raw_value_df.columns
cols

Index(['Premature death raw value', 'Poor or fair health raw value',
       'Poor physical health days raw value',
       'Poor mental health days raw value', 'Low birthweight raw value',
       'Adult smoking raw value', 'Adult obesity raw value',
       'Food environment index raw value', 'Physical inactivity raw value',
       'Access to exercise opportunities raw value',
       'Excessive drinking raw value',
       'Alcohol-impaired driving deaths raw value',
       'Sexually transmitted infections raw value', 'Teen births raw value',
       'Uninsured raw value', 'Primary care physicians raw value',
       'Dentists raw value', 'Mental health providers raw value',
       'Preventable hospital stays raw value',
       'Mammography screening raw value', 'Flu vaccinations raw value',
       'High school completion raw value', 'Some college raw value',
       'Unemployment raw value', 'Children in poverty raw value',
       'Income inequality raw value',
       'Children in single-parent households raw value',
       'Social associations raw value', 'Violent crime raw value',
       'Injury deaths raw value',
       'Air pollution - particulate matter raw value',
       'Drinking water violations raw value',
       'Severe housing problems raw value', 'Driving alone to work raw value',
       'Long commute - driving alone raw value',
       'COVID-19 age-adjusted mortality raw value',
       'Life expectancy raw value',
       'Premature age-adjusted mortality raw value',
       'Child mortality raw value', 'Infant mortality raw value',
       'Frequent physical distress raw value',
       'Frequent mental distress raw value', 'Diabetes prevalence raw value',
       'HIV prevalence raw value', 'Food insecurity raw value',
       'Limited access to healthy foods raw value',
       'Drug overdose deaths raw value',
       'Motor vehicle crash deaths raw value', 'Insufficient sleep raw value',
       'Uninsured adults raw value', 'Uninsured children raw value',
       'Other primary care providers raw value',
       'High school graduation raw value', 'Disconnected youth raw value',
       'Reading scores raw value', 'Math scores raw value',
       'School segregation raw value', 'School funding adequacy raw value',
       'Gender pay gap raw value', 'Median household income raw value',
       'Children eligible for free or reduced price lunch raw value',
       'Residential segregation - Black/white raw value',
       'Residential segregation - non-white/white raw value',
       'Childcare cost burden raw value', 'Childcare centers raw value',
       'Homicides raw value', 'Suicides raw value',
       'Firearm fatalities raw value', 'Juvenile arrests raw value',
       'Traffic volume raw value', 'Homeownership raw value',
       'Severe housing cost burden raw value', 'Broadband access raw value',
       'Population raw value', '% below 18 years of age raw value',
       '% 65 and older raw value', '% non-Hispanic Black raw value',
       '% American Indian & Alaska Native raw value', '% Asian raw value',
       '% Native Hawaiian/Other Pacific Islander raw value',
       '% Hispanic raw value', '% non-Hispanic white raw value',
       '% not proficient in English raw value', '% female raw value',
       '% rural raw value'],
      dtype='object')

In [53]:
short_columns = cols.str.removesuffix(' raw value')
print(len(short_columns))
short_columns[:50]

85

Index(['Premature death', 'Poor or fair health', 'Poor physical health days',
       'Poor mental health days', 'Low birthweight', 'Adult smoking',
       'Adult obesity', 'Food environment index', 'Physical inactivity',
       'Access to exercise opportunities', 'Excessive drinking',
       'Alcohol-impaired driving deaths', 'Sexually transmitted infections',
       'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists',
       'Mental health providers', 'Preventable hospital stays',
       'Mammography screening', 'Flu vaccinations', 'High school completion',
       'Some college', 'Unemployment', 'Children in poverty',
       'Income inequality', 'Children in single-parent households',
       'Social associations', 'Violent crime', 'Injury deaths',
       'Air pollution - particulate matter', 'Drinking water violations',
       'Severe housing problems', 'Driving alone to work',
       'Long commute - driving alone', 'COVID-19 age-adjusted mortality',
       'Life expectancy', 'Premature age-adjusted mortality',
       'Child mortality', 'Infant mortality', 'Frequent physical distress',
       'Frequent mental distress', 'Diabetes prevalence', 'HIV prevalence',
       'Food insecurity', 'Limited access to healthy foods',
       'Drug overdose deaths', 'Motor vehicle crash deaths',
       'Insufficient sleep', 'Uninsured adults'],
      dtype='object')

In [54]:
short_columns[-50:]

Index(['COVID-19 age-adjusted mortality', 'Life expectancy',
       'Premature age-adjusted mortality', 'Child mortality',
       'Infant mortality', 'Frequent physical distress',
       'Frequent mental distress', 'Diabetes prevalence', 'HIV prevalence',
       'Food insecurity', 'Limited access to healthy foods',
       'Drug overdose deaths', 'Motor vehicle crash deaths',
       'Insufficient sleep', 'Uninsured adults', 'Uninsured children',
       'Other primary care providers', 'High school graduation',
       'Disconnected youth', 'Reading scores', 'Math scores',
       'School segregation', 'School funding adequacy', 'Gender pay gap',
       'Median household income',
       'Children eligible for free or reduced price lunch',
       'Residential segregation - Black/white',
       'Residential segregation - non-white/white', 'Childcare cost burden',
       'Childcare centers', 'Homicides', 'Suicides', 'Firearm fatalities',
       'Juvenile arrests', 'Traffic volume', 'Homeownership',
       'Severe housing cost burden', 'Broadband access', 'Population',
       '% below 18 years of age', '% 65 and older', '% non-Hispanic Black',
       '% American Indian & Alaska Native', '% Asian',
       '% Native Hawaiian/Other Pacific Islander', '% Hispanic',
       '% non-Hispanic white', '% not proficient in English', '% female',
       '% rural'],
      dtype='object')

In [20]:
# Rename column names wiht short names which removed "raw value"
short_raw_value_df = raw_value_df.set_axis(short_columns, axis=1, inplace=False) # return a copy df.
short_raw_value_df

,Premature death,Poor or fair health,Poor physical health days,Poor mental health days,Low birthweight,Adult smoking,Adult obesity,Food environment index,Physical inactivity,Access to exercise opportunities,...,% 65 and older,% non-Hispanic Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% non-Hispanic white,% not proficient in English,% female,% rural
3,8027.3947267,0.201,4.5100424038,5.4190677155,0.0973815192,0.197,0.353,6.5,0.322,0.6275860805,...,0.1617597293,0.2031881735,0.0047377327,0.0117018434,0.0010864725,0.0310089946,0.731659097,0.0069269521,0.5150770327,0.4200216232
4,8118.3582061,0.172,4.168866136,5.173915124,0.0838573118,0.199,0.296,7.4,0.276,0.745079966,...,0.2158212197,0.0847889326,0.0077980871,0.0110298447,0.0006629246,0.046339304,0.8330825559,0.0077206791,0.5158905651,0.4227909911
5,12876.760319,0.311,5.8844146337,6.1098993294,0.1191467222,0.278,0.404,5.7,0.416,0.498379284,...,0.2026109236,0.4780999634,0.0069949978,0.0045548823,0.0020334296,0.0467282118,0.452641425,0.0182746687,0.4718370003,0.677896347
6,11191.474323,0.25,5.161337369,5.8460957209,0.1003307607,0.252,0.412,7.6,0.377,0.1060440759,...,0.1707625587,0.2097940007,0.0046078786,0.002574991,0.0012197326,0.0293187568,0.741778099,0.0035509682,0.4681514275,0.6835260746
7,10787.014541,0.232,4.9483926568,5.7382383487,0.0785988894,0.222,0.387,7.8,0.333,0.23376714,...,0.1900343821,0.0152732425,0.0062889822,0.0038010332,0.0012094197,0.0954404879,0.8679832063,0.014764977,0.5055719691,0.8995150204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,8419.275418,0.163,3.495993,3.93355,0.101337,0.17,0.335,8.1,0.252,0.830731,...,0.137417,0.010991,0.014482,0.010077,0.001781,0.161882,0.791953,0.007929,0.483608,0.109163
3191,3283.066198,0.116,2.779692,3.305173,0.080655,0.113,0.222,8.7,0.185,0.964967,...,0.165979,0.007363,0.009916,0.015491,0.001787,0.149508,0.810146,0.029942,0.481338,0.464309
3192,9358.208153,0.172,3.792121,4.268578,0.095438,0.188,0.298,8.3,0.278,0.788806,...,0.156567,0.005689,0.016077,0.005293,0.001583,0.099035,0.868068,0.012533,0.49394,0.430959
3193,7073.941804,0.173,3.660729,4.040619,0.067114,0.176,0.289,8.3,0.259,0.76292,...,0.232861,0.00451,0.016753,0.008634,0.000773,0.141624,0.824742,0.002136,0.490464,0.359545
3194,5149.435226,0.16,3.703659,4.180846,0.067982,0.192,0.334,7.6,0.265,0.282325,...,0.224677,0.006822,0.019872,0.014534,0.000297,0.04108,0.900638,0.00197,0.475308,0.545366

In [21]:
short_raw_value_df[short_columns] = short_raw_value_df[short_columns].apply(pd.to_numeric, errors='coerce', axis=1)
short_raw_value_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3175 entries, 3 to 3194
Data columns (total 85 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Premature death                                    3115 non-null   float64
 1   Poor or fair health                                3175 non-null   float64
 2   Poor physical health days                          3175 non-null   float64
 3   Poor mental health days                            3175 non-null   float64
 4   Low birthweight                                    3069 non-null   float64
 5   Adult smoking                                      3175 non-null   float64
 6   Adult obesity                                      3175 non-null   float64
 7   Food environment index                             3142 non-null   float64
 8   Physical inactivity                                3175 non-null   float64
 9   Access to exercise opportunities                   3099 non-null   float64
 10  Excessive drinking                                 3175 non-null   float64
 11  Alcohol-impaired driving deaths                    3148 non-null   float64
 12  Sexually transmitted infections                    3057 non-null   float64
 13  Teen births                                        2986 non-null   float64
 14  Uninsured                                          3174 non-null   float64
 15  Primary care physicians                            3022 non-null   float64
 16  Dentists                                           3085 non-null   float64
 17  Mental health providers                            2971 non-null   float64
 18  Preventable hospital stays                         3122 non-null   float64
 19  Mammography screening                              3155 non-null   float64
 20  Flu vaccinations                                   3156 non-null   float64
 21  High school completion                             3175 non-null   float64
 22  Some college                                       3175 non-null   float64
 23  Unemployment                                       3174 non-null   float64
 24  Children in poverty                                3174 non-null   float64
 25  Income inequality                                  3169 non-null   float64
 26  Children in single-parent households               3174 non-null   float64
 27  Social associations                                3175 non-null   float64
 28  Violent crime                                      2984 non-null   float64
 29  Injury deaths                                      3070 non-null   float64
 30  Air pollution - particulate matter                 3148 non-null   float64
 31  Drinking water violations                          3132 non-null   float64
 32  Severe housing problems                            3175 non-null   float64
 33  Driving alone to work                              3174 non-null   float64
 34  Long commute - driving alone                       3175 non-null   float64
 35  COVID-19 age-adjusted mortality                    2597 non-null   float64
 36  Life expectancy                                    3105 non-null   float64
 37  Premature age-adjusted mortality                   3115 non-null   float64
 38  Child mortality                                    1917 non-null   float64
 39  Infant mortality                                   1250 non-null   float64
 40  Frequent physical distress                         3175 non-null   float64
 41  Frequent mental distress                           3175 non-null   float64
 42  Diabetes prevalence                                3175 non-null   float64
 43  HIV prevalence                                     2716 non-null   float64
 44  Food insecurity                                    3175 non-null   float64
 45  Limited access to healthy foods                    3142 non-null   float64
 46  Drug overdose deaths                               1830 non-null   float64
 47  Motor vehicle crash deaths                         2724 non-null   float64
 48  Insufficient sleep                                 3175 non-null   float64
 49  Uninsured adults                                   3174 non-null   float64
 50  Uninsured children                                 3174 non-null   float64
 51  Other primary care providers                       3161 non-null   float64
 52  High school graduation                             2516 non-null   float64
 53  Disconnected youth                                 1254 non-null   float64
 54  Reading scores                                     2809 non-null   float64
 55  Math scores                                        2722 non-null   float64
 56  School segregation                                 2933 non-null   float64
 57  School funding adequacy                            3091 non-null   float64
 58  Gender pay gap                                     3171 non-null   float64
 59  Median household income                            3173 non-null   float64
 60  Children eligible for free or reduced price lunch  3121 non-null   float64
 61  Residential segregation - Black/white              2111 non-null   float64
 62  Residential segregation - non-white/white          2883 non-null   float64
 63  Childcare cost burden                              3173 non-null   float64
 64  Childcare centers                                  3002 non-null   float64
 65  Homicides                                          1359 non-null   float64
 66  Suicides                                           2466 non-null   float64
 67  Firearm fatalities                                 2304 non-null   float64
 68  Juvenile arrests                                   1985 non-null   float64
 69  Traffic volume                                     3175 non-null   float64
 70  Homeownership                                      3175 non-null   float64
 71  Severe housing cost burden                         3171 non-null   float64
 72  Broadband access                                   3175 non-null   float64
 73  Population                                         3175 non-null   float64
 74  % below 18 years of age                            3175 non-null   float64
 75  % 65 and older                                     3175 non-null   float64
 76  % non-Hispanic Black                               3175 non-null   float64
 77  % American Indian & Alaska Native                  3175 non-null   float64
 78  % Asian                                            3175 non-null   float64
 79  % Native Hawaiian/Other Pacific Islander           3175 non-null   float64
 80  % Hispanic                                         3175 non-null   float64
 81  % non-Hispanic white                               3175 non-null   float64
 82  % not proficient in English                        3175 non-null   float64
 83  % female                                           3175 non-null   float64
 84  % rural                                            3168 non-null   float64
dtypes: float64(85)
memory usage: 2.1 MB

In [22]:
new_health_df = county_df[['State FIPS Code',
                        'County FIPS Code',
                        '5-digit FIPS Code',
                        'State Abbreviation',
                        'Name']]
new_health_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name
3,01,001,01001,AL,Autauga County
4,01,003,01003,AL,Baldwin County
5,01,005,01005,AL,Barbour County
6,01,007,01007,AL,Bibb County
7,01,009,01009,AL,Blount County
...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County
3191,56,39,56039,WY,Teton County
3192,56,41,56041,WY,Uinta County
3193,56,43,56043,WY,Washakie County
3194,56,45,56045,WY,Weston County

In [23]:
new_health_df['COUNTY_NAME'] = new_health_df['Name'].str.removesuffix(' County')
new_health_df

/var/folders/fx/3xjkq6_j0w52ql5m_lv0vsbr0000gn/T/ipykernel_2354/3970323800.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_health_df['COUNTY_NAME'] = new_health_df['Name'].str.removesuffix(' County')

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,Name,COUNTY_NAME
3,01,001,01001,AL,Autauga County,Autauga
4,01,003,01003,AL,Baldwin County,Baldwin
5,01,005,01005,AL,Barbour County,Barbour
6,01,007,01007,AL,Bibb County,Bibb
7,01,009,01009,AL,Blount County,Blount
...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater County,Sweetwater
3191,56,39,56039,WY,Teton County,Teton
3192,56,41,56041,WY,Uinta County,Uinta
3193,56,43,56043,WY,Washakie County,Washakie
3194,56,45,56045,WY,Weston County,Weston

In [24]:
new_health_df = new_health_df.drop(labels="Name", axis=1)
new_health_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,COUNTY_NAME
3,01,001,01001,AL,Autauga
4,01,003,01003,AL,Baldwin
5,01,005,01005,AL,Barbour
6,01,007,01007,AL,Bibb
7,01,009,01009,AL,Blount
...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater
3191,56,39,56039,WY,Teton
3192,56,41,56041,WY,Uinta
3193,56,43,56043,WY,Washakie
3194,56,45,56045,WY,Weston

In [25]:
new_health_df = new_health_df.merge(short_raw_value_df, left_index=True, right_index=True)
new_health_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,COUNTY_NAME,Premature death,Poor or fair health,Poor physical health days,Poor mental health days,Low birthweight,...,% 65 and older,% non-Hispanic Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% non-Hispanic white,% not proficient in English,% female,% rural
3,01,001,01001,AL,Autauga,8027.394727,0.201,4.510042,5.419068,0.097382,...,0.161760,0.203188,0.004738,0.011702,0.001086,0.031009,0.731659,0.006927,0.515077,0.420022
4,01,003,01003,AL,Baldwin,8118.358206,0.172,4.168866,5.173915,0.083857,...,0.215821,0.084789,0.007798,0.011030,0.000663,0.046339,0.833083,0.007721,0.515891,0.422791
5,01,005,01005,AL,Barbour,12876.760319,0.311,5.884415,6.109899,0.119147,...,0.202611,0.478100,0.006995,0.004555,0.002033,0.046728,0.452641,0.018275,0.471837,0.677896
6,01,007,01007,AL,Bibb,11191.474323,0.250,5.161337,5.846096,0.100331,...,0.170763,0.209794,0.004608,0.002575,0.001220,0.029319,0.741778,0.003551,0.468151,0.683526
7,01,009,01009,AL,Blount,10787.014541,0.232,4.948393,5.738238,0.078599,...,0.190034,0.015273,0.006289,0.003801,0.001209,0.095440,0.867983,0.014765,0.505572,0.899515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater,8419.275418,0.163,3.495993,3.933550,0.101337,...,0.137417,0.010991,0.014482,0.010077,0.001781,0.161882,0.791953,0.007929,0.483608,0.109163
3191,56,39,56039,WY,Teton,3283.066198,0.116,2.779692,3.305173,0.080655,...,0.165979,0.007363,0.009916,0.015491,0.001787,0.149508,0.810146,0.029942,0.481338,0.464309
3192,56,41,56041,WY,Uinta,9358.208153,0.172,3.792121,4.268578,0.095438,...,0.156567,0.005689,0.016077,0.005293,0.001583,0.099035,0.868068,0.012533,0.493940,0.430959
3193,56,43,56043,WY,Washakie,7073.941804,0.173,3.660729,4.040619,0.067114,...,0.232861,0.004510,0.016753,0.008634,0.000773,0.141624,0.824742,0.002136,0.490464,0.359545
3194,56,45,56045,WY,Weston,5149.435226,0.160,3.703659,4.180846,0.067982,...,0.224677,0.006822,0.019872,0.014534,0.000297,0.041080,0.900638,0.001970,0.475308,0.545366

In [26]:
new_health_df.info()
new_health_df

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3175 entries, 3 to 3194
Data columns (total 90 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   State FIPS Code                                    3175 non-null   object
 1   County FIPS Code                                   3175 non-null   object
 2   5-digit FIPS Code                                  3175 non-null   object
 3   State Abbreviation                                 3175 non-null   object
 4   COUNTY_NAME                                        3175 non-null   object
 5   Premature death                                    3115 non-null   float64
 6   Poor or fair health                                3175 non-null   float64
 7   Poor physical health days                          3175 non-null   float64
 8   Poor mental health days                            3175 non-null   float64
 9   Low birthweight                                    3069 non-null   float64
 10  Adult smoking                                      3175 non-null   float64
 11  Adult obesity                                      3175 non-null   float64
 12  Food environment index                             3142 non-null   float64
 13  Physical inactivity                                3175 non-null   float64
 14  Access to exercise opportunities                   3099 non-null   float64
 15  Excessive drinking                                 3175 non-null   float64
 16  Alcohol-impaired driving deaths                    3148 non-null   float64
 17  Sexually transmitted infections                    3057 non-null   float64
 18  Teen births                                        2986 non-null   float64
 19  Uninsured                                          3174 non-null   float64
 20  Primary care physicians                            3022 non-null   float64
 21  Dentists                                           3085 non-null   float64
 22  Mental health providers                            2971 non-null   float64
 23  Preventable hospital stays                         3122 non-null   float64
 24  Mammography screening                              3155 non-null   float64
 25  Flu vaccinations                                   3156 non-null   float64
 26  High school completion                             3175 non-null   float64
 27  Some college                                       3175 non-null   float64
 28  Unemployment                                       3174 non-null   float64
 29  Children in poverty                                3174 non-null   float64
 30  Income inequality                                  3169 non-null   float64
 31  Children in single-parent households               3174 non-null   float64
 32  Social associations                                3175 non-null   float64
 33  Violent crime                                      2984 non-null   float64
 34  Injury deaths                                      3070 non-null   float64
 35  Air pollution - particulate matter                 3148 non-null   float64
 36  Drinking water violations                          3132 non-null   float64
 37  Severe housing problems                            3175 non-null   float64
 38  Driving alone to work                              3174 non-null   float64
 39  Long commute - driving alone                       3175 non-null   float64
 40  COVID-19 age-adjusted mortality                    2597 non-null   float64
 41  Life expectancy                                    3105 non-null   float64
 42  Premature age-adjusted mortality                   3115 non-null   float64
 43  Child mortality                                    1917 non-null   float64
 44  Infant mortality                                   1250 non-null   float64
 45  Frequent physical distress                         3175 non-null   float64
 46  Frequent mental distress                           3175 non-null   float64
 47  Diabetes prevalence                                3175 non-null   float64
 48  HIV prevalence                                     2716 non-null   float64
 49  Food insecurity                                    3175 non-null   float64
 50  Limited access to healthy foods                    3142 non-null   float64
 51  Drug overdose deaths                               1830 non-null   float64
 52  Motor vehicle crash deaths                         2724 non-null   float64
 53  Insufficient sleep                                 3175 non-null   float64
 54  Uninsured adults                                   3174 non-null   float64
 55  Uninsured children                                 3174 non-null   float64
 56  Other primary care providers                       3161 non-null   float64
 57  High school graduation                             2516 non-null   float64
 58  Disconnected youth                                 1254 non-null   float64
 59  Reading scores                                     2809 non-null   float64
 60  Math scores                                        2722 non-null   float64
 61  School segregation                                 2933 non-null   float64
 62  School funding adequacy                            3091 non-null   float64
 63  Gender pay gap                                     3171 non-null   float64
 64  Median household income                            3173 non-null   float64
 65  Children eligible for free or reduced price lunch  3121 non-null   float64
 66  Residential segregation - Black/white              2111 non-null   float64
 67  Residential segregation - non-white/white          2883 non-null   float64
 68  Childcare cost burden                              3173 non-null   float64
 69  Childcare centers                                  3002 non-null   float64
 70  Homicides                                          1359 non-null   float64
 71  Suicides                                           2466 non-null   float64
 72  Firearm fatalities                                 2304 non-null   float64
 73  Juvenile arrests                                   1985 non-null   float64
 74  Traffic volume                                     3175 non-null   float64
 75  Homeownership                                      3175 non-null   float64
 76  Severe housing cost burden                         3171 non-null   float64
 77  Broadband access                                   3175 non-null   float64
 78  Population                                         3175 non-null   float64
 79  % below 18 years of age                            3175 non-null   float64
 80  % 65 and older                                     3175 non-null   float64
 81  % non-Hispanic Black                               3175 non-null   float64
 82  % American Indian & Alaska Native                  3175 non-null   float64
 83  % Asian                                            3175 non-null   float64
 84  % Native Hawaiian/Other Pacific Islander           3175 non-null   float64
 85  % Hispanic                                         3175 non-null   float64
 86  % non-Hispanic white                               3175 non-null   float64
 87  % not proficient in English                        3175 non-null   float64
 88  % female                                           3175 non-null   float64
 89  % rural                                            3168 non-null   float64
dtypes: float64(85), object(5)
memory usage: 2.3+ MB

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,COUNTY_NAME,Premature death,Poor or fair health,Poor physical health days,Poor mental health days,Low birthweight,...,% 65 and older,% non-Hispanic Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% non-Hispanic white,% not proficient in English,% female,% rural
3,01,001,01001,AL,Autauga,8027.394727,0.201,4.510042,5.419068,0.097382,...,0.161760,0.203188,0.004738,0.011702,0.001086,0.031009,0.731659,0.006927,0.515077,0.420022
4,01,003,01003,AL,Baldwin,8118.358206,0.172,4.168866,5.173915,0.083857,...,0.215821,0.084789,0.007798,0.011030,0.000663,0.046339,0.833083,0.007721,0.515891,0.422791
5,01,005,01005,AL,Barbour,12876.760319,0.311,5.884415,6.109899,0.119147,...,0.202611,0.478100,0.006995,0.004555,0.002033,0.046728,0.452641,0.018275,0.471837,0.677896
6,01,007,01007,AL,Bibb,11191.474323,0.250,5.161337,5.846096,0.100331,...,0.170763,0.209794,0.004608,0.002575,0.001220,0.029319,0.741778,0.003551,0.468151,0.683526
7,01,009,01009,AL,Blount,10787.014541,0.232,4.948393,5.738238,0.078599,...,0.190034,0.015273,0.006289,0.003801,0.001209,0.095440,0.867983,0.014765,0.505572,0.899515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,56,37,56037,WY,Sweetwater,8419.275418,0.163,3.495993,3.933550,0.101337,...,0.137417,0.010991,0.014482,0.010077,0.001781,0.161882,0.791953,0.007929,0.483608,0.109163
3191,56,39,56039,WY,Teton,3283.066198,0.116,2.779692,3.305173,0.080655,...,0.165979,0.007363,0.009916,0.015491,0.001787,0.149508,0.810146,0.029942,0.481338,0.464309
3192,56,41,56041,WY,Uinta,9358.208153,0.172,3.792121,4.268578,0.095438,...,0.156567,0.005689,0.016077,0.005293,0.001583,0.099035,0.868068,0.012533,0.493940,0.430959
3193,56,43,56043,WY,Washakie,7073.941804,0.173,3.660729,4.040619,0.067114,...,0.232861,0.004510,0.016753,0.008634,0.000773,0.141624,0.824742,0.002136,0.490464,0.359545
3194,56,45,56045,WY,Weston,5149.435226,0.160,3.703659,4.180846,0.067982,...,0.224677,0.006822,0.019872,0.014534,0.000297,0.041080,0.900638,0.001970,0.475308,0.545366

In [27]:
new_health_df = new_health_df.rename(columns={"COUNTY_NAME":"County_Name"})

In [28]:
print(len(new_health_df["State Abbreviation"].unique()))
new_health_df["State Abbreviation"].unique()

51

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [29]:
new_health_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3175 entries, 3 to 3194
Data columns (total 90 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   State FIPS Code                                    3175 non-null   object
 1   County FIPS Code                                   3175 non-null   object
 2   5-digit FIPS Code                                  3175 non-null   object
 3   State Abbreviation                                 3175 non-null   object
 4   County_Name                                        3175 non-null   object
 5   Premature death                                    3115 non-null   float64
 6   Poor or fair health                                3175 non-null   float64
 7   Poor physical health days                          3175 non-null   float64
 8   Poor mental health days                            3175 non-null   float64
 9   Low birthweight                                    3069 non-null   float64
 10  Adult smoking                                      3175 non-null   float64
 11  Adult obesity                                      3175 non-null   float64
 12  Food environment index                             3142 non-null   float64
 13  Physical inactivity                                3175 non-null   float64
 14  Access to exercise opportunities                   3099 non-null   float64
 15  Excessive drinking                                 3175 non-null   float64
 16  Alcohol-impaired driving deaths                    3148 non-null   float64
 17  Sexually transmitted infections                    3057 non-null   float64
 18  Teen births                                        2986 non-null   float64
 19  Uninsured                                          3174 non-null   float64
 20  Primary care physicians                            3022 non-null   float64
 21  Dentists                                           3085 non-null   float64
 22  Mental health providers                            2971 non-null   float64
 23  Preventable hospital stays                         3122 non-null   float64
 24  Mammography screening                              3155 non-null   float64
 25  Flu vaccinations                                   3156 non-null   float64
 26  High school completion                             3175 non-null   float64
 27  Some college                                       3175 non-null   float64
 28  Unemployment                                       3174 non-null   float64
 29  Children in poverty                                3174 non-null   float64
 30  Income inequality                                  3169 non-null   float64
 31  Children in single-parent households               3174 non-null   float64
 32  Social associations                                3175 non-null   float64
 33  Violent crime                                      2984 non-null   float64
 34  Injury deaths                                      3070 non-null   float64
 35  Air pollution - particulate matter                 3148 non-null   float64
 36  Drinking water violations                          3132 non-null   float64
 37  Severe housing problems                            3175 non-null   float64
 38  Driving alone to work                              3174 non-null   float64
 39  Long commute - driving alone                       3175 non-null   float64
 40  COVID-19 age-adjusted mortality                    2597 non-null   float64
 41  Life expectancy                                    3105 non-null   float64
 42  Premature age-adjusted mortality                   3115 non-null   float64
 43  Child mortality                                    1917 non-null   float64
 44  Infant mortality                                   1250 non-null   float64
 45  Frequent physical distress                         3175 non-null   float64
 46  Frequent mental distress                           3175 non-null   float64
 47  Diabetes prevalence                                3175 non-null   float64
 48  HIV prevalence                                     2716 non-null   float64
 49  Food insecurity                                    3175 non-null   float64
 50  Limited access to healthy foods                    3142 non-null   float64
 51  Drug overdose deaths                               1830 non-null   float64
 52  Motor vehicle crash deaths                         2724 non-null   float64
 53  Insufficient sleep                                 3175 non-null   float64
 54  Uninsured adults                                   3174 non-null   float64
 55  Uninsured children                                 3174 non-null   float64
 56  Other primary care providers                       3161 non-null   float64
 57  High school graduation                             2516 non-null   float64
 58  Disconnected youth                                 1254 non-null   float64
 59  Reading scores                                     2809 non-null   float64
 60  Math scores                                        2722 non-null   float64
 61  School segregation                                 2933 non-null   float64
 62  School funding adequacy                            3091 non-null   float64
 63  Gender pay gap                                     3171 non-null   float64
 64  Median household income                            3173 non-null   float64
 65  Children eligible for free or reduced price lunch  3121 non-null   float64
 66  Residential segregation - Black/white              2111 non-null   float64
 67  Residential segregation - non-white/white          2883 non-null   float64
 68  Childcare cost burden                              3173 non-null   float64
 69  Childcare centers                                  3002 non-null   float64
 70  Homicides                                          1359 non-null   float64
 71  Suicides                                           2466 non-null   float64
 72  Firearm fatalities                                 2304 non-null   float64
 73  Juvenile arrests                                   1985 non-null   float64
 74  Traffic volume                                     3175 non-null   float64
 75  Homeownership                                      3175 non-null   float64
 76  Severe housing cost burden                         3171 non-null   float64
 77  Broadband access                                   3175 non-null   float64
 78  Population                                         3175 non-null   float64
 79  % below 18 years of age                            3175 non-null   float64
 80  % 65 and older                                     3175 non-null   float64
 81  % non-Hispanic Black                               3175 non-null   float64
 82  % American Indian & Alaska Native                  3175 non-null   float64
 83  % Asian                                            3175 non-null   float64
 84  % Native Hawaiian/Other Pacific Islander           3175 non-null   float64
 85  % Hispanic                                         3175 non-null   float64
 86  % non-Hispanic white                               3175 non-null   float64
 87  % not proficient in English                        3175 non-null   float64
 88  % female                                           3175 non-null   float64
 89  % rural                                            3168 non-null   float64
dtypes: float64(85), object(5)
memory usage: 2.3+ MB

In [30]:
file_path = "Resources/County_level_Aggregate_Expenditure_and_Risk_Score_Data_on_Assignable_Beneficiaries_2021.csv"
# DataSource 1: https://data.cms.gov/medicare-shared-savings-program/county-level-aggregate-expenditure-and-risk-score-data-on-assignable-beneficiaries/data/2021
# DataSource 2: https://data.cms.gov/resources/county-level-aggregate-expenditure-and-risk-score-data-on-assignable-beneficiaries-data-dictionary
medicare_df = pd.read_csv(file_path)
medicare_df

,Year,State_Name,County_Name,State_ID,County_ID,Per_Capita_Exp_ESRD,Avg_Risk_Score_ESRD,Person_Years_ESRD,Per_Capita_Exp_DIS,Avg_Risk_Score_DIS,Person_Years_DIS,Per_Capita_Exp_AGDU,Avg_Risk_Score_AGDU,Person_Years_AGDU,Per_Capita_Exp_AGND,Avg_Risk_Score_AGND,Person_Years_AGND
0,2021,Alabama,Autauga,1,0,65037.23,0.96432,33.58,8366.2,0.91364,498.33,20447.27,0.91945,102.67,9951.78,1.02646,2882.17
1,2021,Alabama,Baldwin,1,10,76910.44,0.99813,101.42,9461.95,0.90255,1709.25,19981.29,0.95975,464.33,10301.61,1.0003,18171.75
2,2021,Alabama,Barbour,1,20,69351.79,0.95766,40.67,11938.99,0.98527,337.58,15417.49,0.91376,194.25,9569,0.98952,1461.42
3,2021,Alabama,Bibb,1,30,103539.35,1.11953,18.58,8945.96,0.86691,302.92,15326.91,0.97027,145.83,10055.76,1.08619,941
4,2021,Alabama,Blount,1,40,69621.7,0.97782,20.75,9324.11,0.89179,501.75,15045.31,0.89998,190.67,10549.07,1.07827,2837.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3212,2021,Wyoming,Washakie,53,210,*,*,*,11535.96,0.82789,135.17,22593.73,0.89905,99.67,10439.03,0.83596,1249.08
3213,2021,Wyoming,Weston,53,220,*,*,*,10511.92,0.75399,83.83,21734.38,0.87307,59.33,11830.63,0.87227,866.5
3214,2021,U.S. Possessions,Mariana Islands,63,50,54520.66,0.74688,83.58,11562.9,0.99798,82.17,*,*,*,5738.92,0.82355,846.92
3215,2021,American Samoa,Unknown,64,999,68376.72,0.74493,20.5,9035.65,0.80345,49.42,22535.9,0.94826,45.5,12553.66,0.862,200.92
3216,2021,Guam,Unknown,65,999,68967.82,0.80917,382.17,11101.04,0.7776,535.83,16866.67,0.69814,30.17,7927.8,0.85274,6241.08

In [31]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

# # invert the dictionary
# abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))

In [32]:
print(len(us_state_to_abbrev))
us_state_to_abbrev.values()

57

dict_values(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'DC', 'AS', 'GU', 'MP', 'PR', 'UM', 'VI'])

In [33]:
medicare_df["State Abbreviation"] = medicare_df["State_Name"].replace(us_state_to_abbrev)
medicare_df

,Year,State_Name,County_Name,State_ID,County_ID,Per_Capita_Exp_ESRD,Avg_Risk_Score_ESRD,Person_Years_ESRD,Per_Capita_Exp_DIS,Avg_Risk_Score_DIS,Person_Years_DIS,Per_Capita_Exp_AGDU,Avg_Risk_Score_AGDU,Person_Years_AGDU,Per_Capita_Exp_AGND,Avg_Risk_Score_AGND,Person_Years_AGND,State Abbreviation
0,2021,Alabama,Autauga,1,0,65037.23,0.96432,33.58,8366.2,0.91364,498.33,20447.27,0.91945,102.67,9951.78,1.02646,2882.17,AL
1,2021,Alabama,Baldwin,1,10,76910.44,0.99813,101.42,9461.95,0.90255,1709.25,19981.29,0.95975,464.33,10301.61,1.0003,18171.75,AL
2,2021,Alabama,Barbour,1,20,69351.79,0.95766,40.67,11938.99,0.98527,337.58,15417.49,0.91376,194.25,9569,0.98952,1461.42,AL
3,2021,Alabama,Bibb,1,30,103539.35,1.11953,18.58,8945.96,0.86691,302.92,15326.91,0.97027,145.83,10055.76,1.08619,941,AL
4,2021,Alabama,Blount,1,40,69621.7,0.97782,20.75,9324.11,0.89179,501.75,15045.31,0.89998,190.67,10549.07,1.07827,2837.42,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3212,2021,Wyoming,Washakie,53,210,*,*,*,11535.96,0.82789,135.17,22593.73,0.89905,99.67,10439.03,0.83596,1249.08,WY
3213,2021,Wyoming,Weston,53,220,*,*,*,10511.92,0.75399,83.83,21734.38,0.87307,59.33,11830.63,0.87227,866.5,WY
3214,2021,U.S. Possessions,Mariana Islands,63,50,54520.66,0.74688,83.58,11562.9,0.99798,82.17,*,*,*,5738.92,0.82355,846.92,U.S. Possessions
3215,2021,American Samoa,Unknown,64,999,68376.72,0.74493,20.5,9035.65,0.80345,49.42,22535.9,0.94826,45.5,12553.66,0.862,200.92,AS
3216,2021,Guam,Unknown,65,999,68967.82,0.80917,382.17,11101.04,0.7776,535.83,16866.67,0.69814,30.17,7927.8,0.85274,6241.08,GU

In [34]:
medicare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3217 entries, 0 to 3216
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 3217 non-null   int64
 1   State_Name           3217 non-null   object
 2   County_Name          3217 non-null   object
 3   State_ID             3217 non-null   int64
 4   County_ID            3217 non-null   int64
 5   Per_Capita_Exp_ESRD  3217 non-null   object
 6   Avg_Risk_Score_ESRD  3217 non-null   object
 7   Person_Years_ESRD    3217 non-null   object
 8   Per_Capita_Exp_DIS   3217 non-null   object
 9   Avg_Risk_Score_DIS   3217 non-null   object
 10  Person_Years_DIS     3217 non-null   object
 11  Per_Capita_Exp_AGDU  3217 non-null   object
 12  Avg_Risk_Score_AGDU  3217 non-null   object
 13  Person_Years_AGDU    3217 non-null   object
 14  Per_Capita_Exp_AGND  3217 non-null   object
 15  Avg_Risk_Score_AGND  3217 non-null   object
 16  Person_Years_AGND    3217 non-null   object
 17  State Abbreviation   3217 non-null   object
dtypes: int64(3), object(15)
memory usage: 452.5+ KB

In [35]:
new_medicare_df = medicare_df.drop(labels=['Year','State_ID', 'County_ID'], axis=1)
new_medicare_df

,State_Name,County_Name,Per_Capita_Exp_ESRD,Avg_Risk_Score_ESRD,Person_Years_ESRD,Per_Capita_Exp_DIS,Avg_Risk_Score_DIS,Person_Years_DIS,Per_Capita_Exp_AGDU,Avg_Risk_Score_AGDU,Person_Years_AGDU,Per_Capita_Exp_AGND,Avg_Risk_Score_AGND,Person_Years_AGND,State Abbreviation
0,Alabama,Autauga,65037.23,0.96432,33.58,8366.2,0.91364,498.33,20447.27,0.91945,102.67,9951.78,1.02646,2882.17,AL
1,Alabama,Baldwin,76910.44,0.99813,101.42,9461.95,0.90255,1709.25,19981.29,0.95975,464.33,10301.61,1.0003,18171.75,AL
2,Alabama,Barbour,69351.79,0.95766,40.67,11938.99,0.98527,337.58,15417.49,0.91376,194.25,9569,0.98952,1461.42,AL
3,Alabama,Bibb,103539.35,1.11953,18.58,8945.96,0.86691,302.92,15326.91,0.97027,145.83,10055.76,1.08619,941,AL
4,Alabama,Blount,69621.7,0.97782,20.75,9324.11,0.89179,501.75,15045.31,0.89998,190.67,10549.07,1.07827,2837.42,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3212,Wyoming,Washakie,*,*,*,11535.96,0.82789,135.17,22593.73,0.89905,99.67,10439.03,0.83596,1249.08,WY
3213,Wyoming,Weston,*,*,*,10511.92,0.75399,83.83,21734.38,0.87307,59.33,11830.63,0.87227,866.5,WY
3214,U.S. Possessions,Mariana Islands,54520.66,0.74688,83.58,11562.9,0.99798,82.17,*,*,*,5738.92,0.82355,846.92,U.S. Possessions
3215,American Samoa,Unknown,68376.72,0.74493,20.5,9035.65,0.80345,49.42,22535.9,0.94826,45.5,12553.66,0.862,200.92,AS
3216,Guam,Unknown,68967.82,0.80917,382.17,11101.04,0.7776,535.83,16866.67,0.69814,30.17,7927.8,0.85274,6241.08,GU

In [36]:
new_medicare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3217 entries, 0 to 3216
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State_Name           3217 non-null   object
 1   County_Name          3217 non-null   object
 2   Per_Capita_Exp_ESRD  3217 non-null   object
 3   Avg_Risk_Score_ESRD  3217 non-null   object
 4   Person_Years_ESRD    3217 non-null   object
 5   Per_Capita_Exp_DIS   3217 non-null   object
 6   Avg_Risk_Score_DIS   3217 non-null   object
 7   Person_Years_DIS     3217 non-null   object
 8   Per_Capita_Exp_AGDU  3217 non-null   object
 9   Avg_Risk_Score_AGDU  3217 non-null   object
 10  Person_Years_AGDU    3217 non-null   object
 11  Per_Capita_Exp_AGND  3217 non-null   object
 12  Avg_Risk_Score_AGND  3217 non-null   object
 13  Person_Years_AGND    3217 non-null   object
 14  State Abbreviation   3217 non-null   object
dtypes: object(15)
memory usage: 377.1+ KB

In [37]:
cols2 = ['Per_Capita_Exp_ESRD', 
         'Avg_Risk_Score_ESRD',
         'Person_Years_ESRD',
         'Per_Capita_Exp_DIS',
         'Avg_Risk_Score_DIS',
         'Person_Years_DIS',
         'Per_Capita_Exp_AGDU',
         'Avg_Risk_Score_AGDU',
         'Person_Years_AGDU',
         'Per_Capita_Exp_AGND',
         'Avg_Risk_Score_AGND',
         'Person_Years_AGND']

In [38]:
new_medicare_df[cols2] = new_medicare_df[cols2].apply(pd.to_numeric, errors='coerce', axis=1)
new_medicare_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3217 entries, 0 to 3216
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State_Name           3217 non-null   object
 1   County_Name          3217 non-null   object
 2   Per_Capita_Exp_ESRD  2311 non-null   float64
 3   Avg_Risk_Score_ESRD  2311 non-null   float64
 4   Person_Years_ESRD    2311 non-null   float64
 5   Per_Capita_Exp_DIS   3159 non-null   float64
 6   Avg_Risk_Score_DIS   3159 non-null   float64
 7   Person_Years_DIS     3159 non-null   float64
 8   Per_Capita_Exp_AGDU  3111 non-null   float64
 9   Avg_Risk_Score_AGDU  3111 non-null   float64
 10  Person_Years_AGDU    3111 non-null   float64
 11  Per_Capita_Exp_AGND  3214 non-null   float64
 12  Avg_Risk_Score_AGND  3214 non-null   float64
 13  Person_Years_AGND    3214 non-null   float64
 14  State Abbreviation   3217 non-null   object
dtypes: float64(12), object(3)
memory usage: 377.1+ KB

In [39]:
new_medicare_df["County_Name"].unique()[:20]

array(['Autauga', 'Baldwin', 'Barbour', 'Bibb', 'Blount', 'Bullock',
       'Butler', 'Calhoun', 'Chambers', 'Cherokee', 'Chilton', 'Choctaw',
       'Clarke', 'Clay', 'Cleburne', 'Coffee', 'Colbert', 'Conecuh',
       'Coosa', 'Covington'], dtype=object)

In [40]:
new_health_df["County_Name"].unique()[:20]

array(['Autauga', 'Baldwin', 'Barbour', 'Bibb', 'Blount', 'Bullock',
       'Butler', 'Calhoun', 'Chambers', 'Cherokee', 'Chilton', 'Choctaw',
       'Clarke', 'Clay', 'Cleburne', 'Coffee', 'Colbert', 'Conecuh',
       'Coosa', 'Covington'], dtype=object)

In [41]:
print(len(new_medicare_df["State Abbreviation"].unique()))
new_medicare_df["State Abbreviation"].unique()
# 5states now shown in health dataset: 'PR', 'Virgin Islands', 'U.S. Possessions', 'AS', 'GU'

56

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN',
       'TX', 'UT', 'VT', 'Virgin Islands', 'VA', 'WA', 'WV', 'WI', 'WY',
       'U.S. Possessions', 'AS', 'GU'], dtype=object)

In [42]:
combined_df = pd.merge(new_health_df, new_medicare_df, on=['State Abbreviation','County_Name'], how="left")
combined_df

,State FIPS Code,County FIPS Code,5-digit FIPS Code,State Abbreviation,County_Name,Premature death,Poor or fair health,Poor physical health days,Poor mental health days,Low birthweight,...,Person_Years_ESRD,Per_Capita_Exp_DIS,Avg_Risk_Score_DIS,Person_Years_DIS,Per_Capita_Exp_AGDU,Avg_Risk_Score_AGDU,Person_Years_AGDU,Per_Capita_Exp_AGND,Avg_Risk_Score_AGND,Person_Years_AGND
0,01,001,01001,AL,Autauga,8027.394727,0.201,4.510042,5.419068,0.097382,...,33.58,8366.20,0.91364,498.33,20447.27,0.91945,102.67,9951.78,1.02646,2882.17
1,01,003,01003,AL,Baldwin,8118.358206,0.172,4.168866,5.173915,0.083857,...,101.42,9461.95,0.90255,1709.25,19981.29,0.95975,464.33,10301.61,1.00030,18171.75
2,01,005,01005,AL,Barbour,12876.760319,0.311,5.884415,6.109899,0.119147,...,40.67,11938.99,0.98527,337.58,15417.49,0.91376,194.25,9569.00,0.98952,1461.42
3,01,007,01007,AL,Bibb,11191.474323,0.250,5.161337,5.846096,0.100331,...,18.58,8945.96,0.86691,302.92,15326.91,0.97027,145.83,10055.76,1.08619,941.00
4,01,009,01009,AL,Blount,10787.014541,0.232,4.948393,5.738238,0.078599,...,20.75,9324.11,0.89179,501.75,15045.31,0.89998,190.67,10549.07,1.07827,2837.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3170,56,37,56037,WY,Sweetwater,8419.275418,0.163,3.495993,3.933550,0.101337,...,28.83,11834.08,0.88365,557.00,19512.86,1.01523,189.42,9113.93,0.89737,3494.50
3171,56,39,56039,WY,Teton,3283.066198,0.116,2.779692,3.305173,0.080655,...,NaN,12832.56,0.77582,70.75,15394.00,0.78165,51.17,8979.45,0.72437,2440.58
3172,56,41,56041,WY,Uinta,9358.208153,0.172,3.792121,4.268578,0.095438,...,14.00,12639.65,0.96239,282.92,21846.03,1.06459,103.42,9638.23,0.88644,1696.25
3173,56,43,56043,WY,Washakie,7073.941804,0.173,3.660729,4.040619,0.067114,...,NaN,11535.96,0.82789,135.17,22593.73,0.89905,99.67,10439.03,0.83596,1249.08
3174,56,45,56045,WY,Weston,5149.435226,0.160,3.703659,4.180846,0.067982,...,NaN,10511.92,0.75399,83.83,21734.38,0.87307,59.33,11830.63,0.87227,866.50

In [43]:
combined_df.to_csv("Resources/health_medicare_2022.csv")